### ISSUE TITLE
[RELEASE] DirectPV v4.0.9

### ISSUE THREAD

**Issue by djwfyi** [minio/directpv-docs#6]
DirectPV [v4.0.9](https://github.com/minio/directpv/releases/tag/v4.0.9) has changes that impact the docs:

- [x] There is a Helm chart for DirectPV ([PR minio/docs#824](https://github.com/minio/directpv/pull/824))
- [x] Adds commands to suspend or resume drives/volumes ([PR minio/docs#842](https://github.com/minio/directpv/pull/842))
- [x] Supports assigning volumes to unique disks ([PR minio/docs#823](https://github.com/minio/directpv/pull/823))
- [x] Corrects upgrade process ([PR minio/docs#851](https://github.com/minio/directpv/pull/851))

**Comment by djwfyi** [comment]
This issue is completed.
